language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - public
    - .cache
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: gh-pages
  if: type = pull_request AND (branch = master OR branch = dev)
