language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run test:coverage
        - npm run build
      after_success:
        - bash ./scripts/deploy.sh
      branch:
        - master
        - dev
    - stage: deploy
      script:
        - npm run build
      after_success:
        - bash ./scripts/deploy.sh
      branch:
        - master
        - dev
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push
env:
  global:
    - GH_USER: jimskretas
    - GH_REPO: react-travis-ci-demo
