language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run test:coverage
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND (branch = master OR branch = dev)
