name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      # - name: Test Coverage for source branch
      #   uses: paambaati/codeclimate-action@v2.6.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: npm run test:coverage
      #     debug: true
      #     coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
      - run: npm run test:coverage
      # - name: Codacy-Coverage
      #   if: ${{ success() }}
      #   run: cat ./coverage/lcov.info | codacy-coverage --token $token
      #   env:
      #     token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{github.workspace}}/coverage/lcov.info
      - run: npm run build
